import type { Metadata } from 'next';
import { Hanken_Grotesk } from 'next/font/google';

import './globals.css';
import 'primereact/resources/themes/tailwind-light/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';

import { PrimeReactI18nProvider } from '@/services/config/i18n';
import { PrimeReactProvider } from 'primereact/api';
import { LocationConsentModal } from '@/component';
import ClientProvider from '@/services/config/ClientProvider';

const HankenGrotesk = Hanken_Grotesk({
  variable: '--font-hanken-grotesk',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Showtime',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${HankenGrotesk.variable} font-hanken-grotesk`}>
        <ClientProvider>
          <PrimeReactI18nProvider>
            <PrimeReactProvider
              value={{
                unstyled: false,
                ripple: false,
                locale: 'pt-BR',
              }}
            >
              <LocationConsentModal />
              {children}
            </PrimeReactProvider>
          </PrimeReactI18nProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
