import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import './globals.css';
import 'primereact/resources/themes/tailwind-light/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';

import { PrimeReactI18nProvider } from '@/services/config/i18n';
import { PrimeReactProvider } from 'primereact/api';
import { Button } from 'primereact/button';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PrimeReactI18nProvider>
          <PrimeReactProvider
            value={{
              unstyled: false,
              ripple: false,
              locale: 'pt-BR',
            }}
          >
            {children}
          </PrimeReactProvider>
        </PrimeReactI18nProvider>
      </body>
    </html>
  );
}
